aws/porting-assistant-dotnet-ui

packages/react/src/components/PortShared/handlePortProjectSubmission.ts

#12 
Change the wrong atttribute to label.

Fix the bug when port with package, the package version is empty

---

packages/electron/src/preload-porting.ts
packages/react/src/components/PortSolution/PortSolutionDashboard.tsx

*Issue #9 , if available:*
Add filter to remove .git file and folder when copy to new locaiton

Remove .git file and folder when copy to new locaiton

---

packages/csharp/PortingAssistant/PortingAssistant.Common/PortingAssistant.Common.csproj
packages/electron/src/electron-backend.ts
packages/react/src/__tests__/selectors.test.ts
packages/react/src/bootstrapElectron.ts
packages/react/src/components/AssessSolution/AssessSolutionDashboard.tsx
packages/react/src/components/AssessSolution/ProjectsTable.tsx
packages/react/src/components/AssessSolution/SolutionSummary.tsx
packages/react/src/components/Dashboard/DashboardTable.tsx
packages/react/src/components/PortShared/NugetPackageUpgrades.tsx
packages/react/src/components/PortShared/handlePortProjectSubmission.ts
packages/react/src/components/Setup/ProfileSelection.tsx
packages/react/src/models/project.ts
packages/react/src/store/sagas/backendSaga.ts
packages/react/src/store/selectors/tableSelectors.ts

#14 
(1) set default value for porting packages
(2) show number of porting actions
(3) only show release version

UI enhancements

---

.commit-msg
package-lock.json
package.json
packages/csharp/PortingAssistant/PortingAssistant.Common/PortingAssistant.Common.csproj
packages/react/src/__tests__/selectors.test.ts
packages/react/src/components/AssessShared/NugetPackageTable.tsx
packages/react/src/store/selectors/tableSelectors.ts

fix: auto pop up commit template
change: add commit hook

feature: Add commit template

---

.commit-msg
commitlint.config.js
package-lock.json
package.json

fix the commit template to comply with the sematic check

fix: fix the commit template

---

packages/electron/src/electron.ts

feature: maxmize the windows

---

packages/react/src/components/AssessShared/FileTable.tsx
packages/react/src/components/AssessShared/NugetPackageTable.tsx
packages/react/src/components/Dashboard/DashboardTable.tsx
packages/react/src/components/PortShared/NugetPackageUpgrades.tsx

#22 
fix the nuget and file table sorting

fix: resolve sorting issue for tables

---

packages/csharp/PortingAssistant/PortingAssistant.Common/Model/ProjectFilePortingRequest.cs
packages/csharp/PortingAssistant/PortingAssistant.Common/PortingAssistant.Common.csproj
packages/csharp/PortingAssistant/PortingAssistant.Common/Services/PortingService.cs
packages/electron/src/electron-backend.ts
packages/electron/src/preload.ts
packages/react/src/bootstrapElectron.ts
packages/react/src/components/PortShared/handlePortProjectSubmission.ts

Update porting interface to match the projects and upgraded packages

fix: match projects with upgraded packages

---

packages/csharp/PortingAssistant/PortingAssistant.Common/Services/AssesmentService.cs
packages/electron/src/telemetry/electron-telemetry.ts
packages/react/src/mockData.ts
packages/react/src/models/project.ts

Add Package version and Project Guid to Api Metrics
Manual Testing of metrics.

fix: add package version and projectGuid to Api Metrics

---

lerna.json
package-lock.json
package.json
packages/csharp/package-lock.json
packages/csharp/package.json
packages/electron/package-lock.json
packages/electron/package.json
packages/electron/src/preload-localStore.ts
packages/integration-test/package-lock.json
packages/integration-test/package.json
packages/react/package-lock.json
packages/react/package.json

feat: bump up version to 1.4.2

---

packages/electron/src/telemetry/electron-telemetry.ts

fix: remove metric logging

---

lerna.json
package-lock.json
package.json
packages/csharp/PortingAssistant/PortingAssistant.Common/PortingAssistant.Common.csproj
packages/csharp/package-lock.json
packages/csharp/package.json
packages/electron/package-lock.json
packages/electron/package.json
packages/electron/src/preload-localStore.ts
packages/integration-test/package-lock.json
packages/integration-test/package.json
packages/react/package-lock.json
packages/react/package.json

feat: bump up version to 1.4.3

---

packages/electron/src/preload-porting.ts

fix: update the copy regex to filter .git file

---

lerna.json
package.json
packages/csharp/package-lock.json
packages/csharp/package.json
packages/electron/package-lock.json
packages/electron/package.json
packages/electron/src/preload-localStore.ts
packages/integration-test/package-lock.json
packages/integration-test/package.json
packages/react/package-lock.json
packages/react/package.json
packages/react/src/constants/externalUrls.ts

feat: bump up version to 1.5.0

---

packages/csharp/PortingAssistant/PortingAssistant.Common/Services/PortingService.cs
packages/electron/src/preload.ts
packages/react/src/bootstrapElectron.ts
packages/react/src/components/AddSolution/AddSolutionForm.tsx
packages/react/src/components/AssessSolution/AssessSolutionDashboard.tsx
packages/react/src/components/Dashboard/DashboardTable.tsx
packages/react/src/components/PortShared/handlePortProjectSubmission.ts
packages/react/src/store/actions/backend.ts
packages/react/src/store/sagas/backendSaga.ts

#34 
Fix the configuration with new PA client

fix: adapt the configuration to new PA client

---

lerna.json
package-lock.json
package.json
packages/csharp/package-lock.json
packages/csharp/package.json
packages/electron/package-lock.json
packages/electron/package.json
packages/electron/src/preload-localStore.ts
packages/integration-test/package-lock.json
packages/integration-test/package.json
packages/react/package-lock.json
packages/react/package.json

feat: bump up version to 1.5.1

---

packages/csharp/PortingAssistant/PortingAssistant.Api/Application.cs
packages/csharp/PortingAssistant/PortingAssistant.Common/PortingAssistant.Common.csproj
packages/react/src/components/AssessShared/useApiAnalysisFlashbarMessage.ts
packages/react/src/components/PortingAssistantFlashbar.tsx

fix: update the flashbar notification for build failure

---

package.json
packages/csharp/package.json
packages/electron/package.json
packages/electron/src/electron.ts
packages/integration-test/package.json
packages/react/package.json

docs: fix the broken links

---

packages/integration-test/package-lock.json
packages/integration-test/src/stability.spec.ts

- Add sanity checks to verify numbers and results from assessment and porting are what we expect.
- Changed test to wait on spinner class for so test won't accidentally move on too soon and get stuck
- Only port up to two projects to save time
- Manual running of test in workspace
- Created new code build, "integration-test" with the beta AWS account

test: add sanity test cases to stability integration test

---

packages/csharp/PortingAssistant/PortingAssistant.Api/Application.cs
packages/csharp/PortingAssistant/PortingAssistant.Api/PortingAssistant.Api.csproj
packages/electron/src/electron-backend.ts
packages/electron/src/preload.ts
packages/react/src/__tests__/selectors.test.ts
packages/react/src/bootstrapElectron.ts
packages/react/src/components/AddSolution/AddSolutionForm.tsx
packages/react/src/components/AssessSolution/AssessSolutionDashboard.tsx
packages/react/src/components/Dashboard/DashboardTable.tsx
packages/react/src/components/PortShared/handlePortProjectSubmission.ts
packages/react/src/setupTests.ts
packages/react/src/store/actions/backend.ts
packages/react/src/store/sagas/backendSaga.ts
packages/react/src/utils/checkInternetAccess.ts

Add function that tries to download file from s3 bucket to check for internet connectivity. Checks on app init and before assessment
Tested manually on my machine. Correctly recognized no internet, and stopped analyzing solution.

fix: add checks for internet access

---

packages/integration-test/README.md

Change NopCommerce 4.3 to NopCommerce 3.1. Solution changed to test porting from framework to core.
Update README.md to reflect changes to integration stability test

docs: update integration test README.md

---

packages/react/src/components/Settings/SettingsDashboard.tsx
packages/react/src/components/Setup/ProfileSelection.tsx
packages/react/src/containers/EditSettings.tsx

docs: update external url

---

packages/csharp/PortingAssistant/PortingAssistant.Api/Application.cs
packages/electron/src/electron-backend.ts
packages/electron/src/preload.ts
packages/integration-test/README.md
packages/react/src/App.tsx
packages/react/src/__tests__/selectors.test.ts
packages/react/src/bootstrapElectron.ts
packages/react/src/constants/messages.ts
packages/react/src/setupTests.ts
packages/react/src/store/sagas/backendSaga.ts
packages/react/src/utils/checkInternetAccess.ts

https://sim.amazon.com/issues/P49559103
- add additional files to try and access from s3 datastore, if any one succeeds treat as success in order to better safeguard against files being removed by accident.
- add additional check function in electron to be called at the beginning of the application, even before profile is selected.

feat: internet check additional changes

---

packages/electron/build-scripts/publish.ts

fix: read config from env

---

lerna.json
package-lock.json
package.json
packages/csharp/package-lock.json
packages/csharp/package.json
packages/electron/package-lock.json
packages/electron/package.json
packages/electron/src/preload-localStore.ts
packages/integration-test/package-lock.json
packages/integration-test/package.json
packages/react/package-lock.json
packages/react/package.json

feat: bump up version to 1.5.3

---

packages/csharp/PortingAssistant/PortingAssistant.Api/PortingAssistant.Api.csproj
packages/csharp/PortingAssistant/PortingAssistant.Common/PortingAssistant.Common.csproj
packages/csharp/PortingAssistant/PortingAssistant.Telemetry/PortingAssistant.Telemetry.csproj

update client references for typo fix

fix: update client references for typo fix

---

packages/electron/src/preload.ts
packages/react/src/components/AssessShared/EnterEmailModal.tsx
packages/react/src/components/Setup/ProfileSelection.tsx
packages/react/src/models/localStoreSchema.ts

#56 
Created a field in Porting Assistant settings to add email. Customer can modify or remove email at any time. Email is stored locally. 
Created a Modal to request customer to provide email. Modal can be placed over any component that requires email to collect the email address first, if it does not exist yet. This email is saved locally and made available to other features that may need it. 
Manual testing
- [ x ] I have read the …

Local email storage feature

---

packages/csharp/PortingAssistant/PortingAssistant.Telemetry/Models/MetricsBase.cs
packages/csharp/PortingAssistant/PortingAssistant.Telemetry/PortingAssistant.Telemetry.csproj

*Issue #39 
Add new property "customerId" to Metrics to populate unique Id (Mac id) to identify customers
Yes
N/A

fix: Add mac ID or similar stuff to track the download in each machine

---

packages/electron/src/electron-backend.ts
packages/electron/src/electron.ts
packages/electron/src/preload-localStore.ts
packages/electron/src/preload.ts
packages/react/src/bootstrapElectron.ts
packages/react/src/components/Sidebar.tsx
packages/react/src/constants/externalUrls.ts
packages/react/src/containers/Dashboard.tsx
packages/react/src/models/localStoreSchema.ts

added release note banner for outdated versions and send feedback link
Added release note banner for outdated versions and send feedback link in sidebar

feat: added release note banner and send feedback link

---

CODEOWNERS

fix: add file level code review

---

packages/integration-test/src/stability.spec.ts

With the new version of the PA, we added additional API types that we look for during assessment, this changes the results we get from assessing our test solutions and the numbers needed to be updated accordingly.
Also ran into some issues where profile selection was taking longer than 10 seconds, causing and error and the test to fail. This did not actually cause any real issues during the test so increased the timeout window to 1 min.
Tested in code-build using this branch.
- [xI used the …

test: update integ test

---

.gitignore
packages/electron/build-scripts/porting-assistant-config.dev.json
packages/react/src/App.tsx
packages/react/src/components/AssessShared/EnterEmailModal.tsx
packages/react/src/components/AssessShared/NugetPackageTable.tsx
packages/react/src/components/Feedback/PackageRuleContribution.tsx
packages/react/src/components/Setup/ProfileSelection.tsx
packages/react/src/constants/paths.ts
packages/react/src/containers/RuleContribution.tsx
packages/react/src/models/locationState.ts

#58 
Completed the rule contribution page for NuGet packages, Validation is not implemented yet. 
Manual
- [ x ] I have read the [CONTRIBUTING](https://github.com/aws/porting-assistant-dotnet-ui/blob/develop/CONTRIBUTING.md) doc
- [ x ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/porting-assistant-dotnet-ui/blob/develop/CONTRIBUTING.md#commit-your-change)
- [ x ] I have updated any necessary documentation, including READMEs and …

Rule contribution page: nuget packages

---

packages/csharp/PortingAssistant/PortingAssistant.Common/Utils/TelemetryCollectionUtils.cs
packages/csharp/PortingAssistant/PortingAssistant.UnitTests/PIIObfuscationUnitTest.cs
packages/csharp/PortingAssistant/PortingAssistant.UnitTests/PortingAssistant.UnitTests.csproj
packages/csharp/PortingAssistant/PortingAssistant.sln

- Add Unit Tests to check obfuscation of PII Data

Add Unit Tests to check obfuscation of PII Data

---

packages/integration-test/src/stability.spec.ts

click add named profile,  check for message when no info is provided and escape out

test: add named profile check

---

packages/csharp/PortingAssistant/PortingAssistant.Api/Application.cs
packages/csharp/PortingAssistant/PortingAssistant.Api/PortingAssistant.Api.csproj
packages/csharp/PortingAssistant/PortingAssistant.Common/Model/RuleContributionRequest.cs
packages/csharp/PortingAssistant/PortingAssistant.Common/Utils/S3UploadUtils.cs
packages/electron/src/electron-backend.ts
packages/electron/src/preload.ts
packages/react/src/__tests__/utils.test.ts
packages/react/src/bootstrapElectron.ts
packages/react/src/components/AssessShared/NugetPackageTable.tsx
packages/react/src/components/Feedback/PackageRuleContribution.tsx
packages/react/src/components/Setup/ProfileSelection.tsx
packages/react/src/containers/RuleContribution.tsx
packages/react/src/utils/uploadToS3Bucket.ts
packages/react/src/utils/validateRuleContrib.ts

#58
Implemented upload to S3. Added AWS SDK to backend. Reading credentials from dev config.
Manual
- [ x ] I have read the [CONTRIBUTING](https://github.com/aws/porting-assistant-dotnet-ui/blob/develop/CONTRIBUTING.md) doc
- [ x ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/porting-assistant-dotnet-ui/blob/develop/CONTRIBUTING.md#commit-your-change)
- [ x ] I have updated any necessary documentation, including READMEs and …

feat: implemented upload to S3

---

packages/csharp/PortingAssistant/PortingAssistant.Common/Services/AssesmentService.cs
packages/csharp/PortingAssistant/PortingAssistant.Common/Utils/TelemetryCollectionUtils.cs
packages/csharp/PortingAssistant/PortingAssistant.Telemetry/Models/SolutionMetrics.cs
packages/csharp/PortingAssistant/PortingAssistant.UnitTests/PIIObfuscationUnitTest.cs

This patch add ApplicationGuid, SolutionGuid and RepositoryUrl to solution metrics.
1. Manually build PA installer exe and install it on a windows machine, run it against a test solution NetFrameworkExample and validate the three fields are added to metrics logs.
2. Also updated unit test.

feat: Add Solution Metrics.

---

packages/csharp/PortingAssistant/PortingAssistant.Telemetry/Utils/LogUploadUtils.cs

feat: upload drift metrics through PA tool

---

packages/csharp/PortingAssistant/PortingAssistant.Api/PortingAssistant.Api.csproj
packages/csharp/PortingAssistant/PortingAssistant.Common/PortingAssistant.Common.csproj
packages/csharp/PortingAssistant/PortingAssistant.Telemetry/PortingAssistant.Telemetry.csproj

feat: Update client version.

---

lerna.json
package-lock.json
package.json
packages/csharp/package-lock.json
packages/csharp/package.json
packages/electron/package-lock.json
packages/electron/package.json
packages/integration-test/package-lock.json
packages/integration-test/package.json
packages/react/package-lock.json
packages/react/package.json

Shan update release version

---

packages/electron/src/preload-localStore.ts

feat: update reducer version

---

packages/electron/build-scripts/publish.ts
packages/electron/src/electron-backend.ts
packages/electron/src/electron.ts
packages/electron/src/preload.ts
packages/electron/src/telemetry/electron-telemetry.ts
packages/react/src/bootstrapElectron.ts
packages/react/src/components/CustomerContribution/CustomerFeedbackModal.tsx
packages/react/src/components/CustomerContribution/PackageRuleContribution.tsx

feat: write react error log and update config

---

packages/integration-test/src/stability.spec.ts
packages/react/src/components/AssessShared/EnterEmailModal.tsx
packages/react/src/components/AssessShared/NugetPackageTable.tsx
packages/react/src/components/AssessSolution/AssessSolutionDashboard.tsx
packages/react/src/components/CustomerContribution/CustomerFeedbackModal.tsx
packages/react/src/components/CustomerContribution/PackageRuleContribution.tsx

feat: update integration test for customer contribution

---

lerna.json
package-lock.json
package.json
packages/csharp/package-lock.json
packages/csharp/package.json
packages/electron/package-lock.json
packages/electron/package.json
packages/electron/src/preload-localStore.ts
packages/integration-test/package-lock.json
packages/integration-test/package.json
packages/react/package-lock.json
packages/react/package.json

feat: bump up version to 1.6.1

---

packages/react/src/containers/Dashboard.tsx

fix: fixed spelling for 'solution' on dashboard ui

---

lerna.json
package-lock.json
package.json
packages/csharp/package.json
packages/electron/package-lock.json
packages/electron/package.json
packages/electron/src/preload-localStore.ts
packages/electron/src/telemetry/electron-telemetry.ts
packages/integration-test/package-lock.json
packages/integration-test/package.json
packages/integration-test/src/stability.spec.ts
packages/react/package-lock.json
packages/react/package.json
packages/react/src/__tests__/selectors.test.ts
packages/react/src/__tests__/utils.test.ts
packages/react/src/components/Setup/ProfileSelection.tsx
packages/react/src/constants/targetversion.ts
packages/react/src/mockData.ts
packages/react/src/store/selectors/solutionSelectors.ts
packages/react/src/utils/getCompatibleApi.ts
packages/react/src/utils/getTargetFramework.ts
packages/react/src/utils/isPortingCompleted.ts

Net6.0 support default value

---

packages/csharp/PortingAssistant/PortingAssistant.Api/PortingAssistant.Api.csproj
packages/csharp/PortingAssistant/PortingAssistant.Common/PortingAssistant.Common.csproj
packages/csharp/PortingAssistant/PortingAssistant.Telemetry/PortingAssistant.Telemetry.csproj
packages/csharp/PortingAssistant/PortingAssistant.UnitTests/PortingAssistant.UnitTests.csproj
packages/csharp/PortingAssistant/PortingAssistant.VisualStudio/PortingAssistant.VisualStudio.csproj

fix: update pa client versions

---

packages/electron/src/telemetry/electron-metrics.ts

Get and pass session token to support short term credentials
Manual testing with short term credentials generated and with regular credentials without a session token

feat: support short term credentials

---

packages/csharp/PortingAssistant/PortingAssistant.Api/PortingAssistant.Api.csproj
packages/csharp/PortingAssistant/PortingAssistant.Common/PortingAssistant.Common.csproj
packages/csharp/PortingAssistant/PortingAssistant.Telemetry/PortingAssistant.Telemetry.csproj
packages/csharp/PortingAssistant/PortingAssistant.Telemetry/Program.cs
packages/csharp/PortingAssistant/PortingAssistant.Telemetry/Utils/LogUploadUtils.cs
packages/csharp/PortingAssistant/PortingAssistant.UnitTests/PortingAssistant.UnitTests.csproj
packages/csharp/PortingAssistant/PortingAssistant.VisualStudio/PortingAssistant.VisualStudio.csproj

Add support for short term creds when uploading telemetry
*Tests*
* Long term creds
* Short term creds
* Short term creds w/o session token
* Expired short term creds

Support temp creds

---

lerna.json
package-lock.json
package.json
packages/csharp/package.json
packages/electron/package-lock.json
packages/electron/package.json
packages/electron/src/preload-localStore.ts
packages/integration-test/package-lock.json
packages/integration-test/package.json
packages/react/package-lock.json
packages/react/package.json

feat: upgrade version to 1.6.4

---

packages/react/src/components/PortConfigurationModal/LocationSection.tsx

fix: Validation copying to sln directory

---

packages/integration-test/package.json
packages/integration-test/src/hooks.ts
packages/integration-test/src/profileCheck.spec.ts
packages/integration-test/src/testRunner.ts

Add UI Tests for Invalid Credentials.
Locally ran the integration tests 
- [ …

fix: add ui tests for invalid credentials

---

.github/workflows/build_test.yml

fix: add hooks to detect aws secrets

---

packages/integration-test/src/constants.ts
packages/integration-test/src/netcore31.spec.ts

fix: add integration tests for webforms and iis config

---

packages/integration-test/src/netcore31.spec.ts

update expected values for nopcommerce test in response to canary and beta build failure

test: update expected values

---

packages/csharp/PortingAssistant/PortingAssistant.Api/Application.cs
packages/csharp/PortingAssistant/PortingAssistant.Common/Utils/HttpServiceUtils.cs
packages/csharp/PortingAssistant/PortingAssistant.UnitTests/HttpServiceUtilsTest.cs

remove try catch because the is completed successfully property will capture a failed request
also update the packages we try to ping in the datastore
Test manually and verify they are valid packages in datastore and that even if using old packages, as long as there is one valid package the check will pass

fix: internet check

---

packages/electron/src/setup.ts
packages/react/src/components/Setup/ProfileSelectionModal.tsx
packages/react/src/models/setup.ts

Add Session Token Field in Profile Add Modal for Short Term Credential Support …

feat: add Session Token to Profile Modal

---

lerna.json
package-lock.json
package.json
packages/csharp/package-lock.json
packages/csharp/package.json
packages/electron/package-lock.json
packages/electron/package.json
packages/electron/src/preload-localStore.ts
packages/integration-test/package-lock.json
packages/integration-test/package.json
packages/react/package-lock.json
packages/react/package.json

* Necessary version numbers updated to 1.6.5

feat: Updated version for latest release to 1.6.5

---

packages/integration-test/src/canary.spec.ts
packages/integration-test/src/netcore31.spec.ts
packages/integration-test/src/stability.spec.ts

- [x ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/porting-assistant-dotnet-ui/blob/develop/CONTRIBUTING.md#commit-your-change)
- [ x] I have added tests that prove my fix is effective or that my feature …

fix: update integ test api numbers

---

packages/integration-test/src/canary.spec.ts

- [x ] I have updated any necessary documentation, including READMEs and comments (where appropriate)
- [ x] I have added tests that prove my fix is effective or that my feature …

fix: update integ test numbers for Miniblog

---

packages/integration-test/src/profileCheck.spec.ts

* Removed integration tests that were acting flaky during build process

fix: Temporarily removed flaky integration tests

---

packages/electron/src/electron-backend.ts

- [x ] I have added tests that prove my fix is effective or that my feature …

fix: move profile change logic to telemetry

---

packages/electron/package-lock.json

fix: update electron package-lock
- [x ] I have read the [CONTRIBUTING](https://github.com/aws/porting-assistant-dotnet-ui/blob/develop/CONTRIBUTING.md) doc
- [x ] I have updated any necessary documentation, including READMEs and comments (where appropriate)
- [x ] I have added tests that prove my fix …

fix: update electron package-lock

---

lerna.json
package-lock.json
package.json
packages/csharp/PortingAssistant/PortingAssistant.Api/PortingAssistant.Api.csproj
packages/csharp/package-lock.json
packages/csharp/package.json
packages/electron/package-lock.json
packages/electron/package.json
packages/electron/src/preload-localStore.ts
packages/integration-test/package-lock.json
packages/integration-test/package.json
packages/react/package-lock.json
packages/react/package.json

feat: update Tool Version to 1.6.6 and bump CTA to 2.1.8
- [x ] I have read the [CONTRIBUTING](https://github.com/aws/porting-assistant-dotnet-ui/blob/develop/CONTRIBUTING.md) doc
- [ x] I have added …

feat: update Tool Version to 1.6.6 and bump CTA to 2.1.8

---

packages/integration-test/src/testRunner.ts
packages/react/src/components/Setup/ProfileSelection.tsx

tests: update integ tests

---

packages/integration-test/src/testRunner.ts
packages/react/src/components/Setup/ProfileSelection.tsx

test: fix integ test

---

packages/csharp/PortingAssistant/PortingAssistant.Api/PortingAssistant.Api.csproj
packages/csharp/PortingAssistant/PortingAssistant.Common/PortingAssistant.Common.csproj
packages/csharp/PortingAssistant/PortingAssistant.Telemetry/PortingAssistant.Telemetry.csproj
packages/csharp/PortingAssistant/PortingAssistant.UnitTests/PortingAssistant.UnitTests.csproj
packages/csharp/PortingAssistant/PortingAssistant.VisualStudio/PortingAssistant.VisualStudio.csproj

feat: update client version to 2.2.2

---

lerna.json
package-lock.json
package.json
packages/csharp/PortingAssistant/PortingAssistant.Common/PortingAssistant.Common.csproj
packages/csharp/PortingAssistant/PortingAssistant.Telemetry/PortingAssistant.Telemetry.csproj
packages/csharp/PortingAssistant/PortingAssistant.UnitTests/PortingAssistant.UnitTests.csproj
packages/csharp/PortingAssistant/PortingAssistant.VisualStudio/PortingAssistant.VisualStudio.csproj
packages/csharp/package-lock.json
packages/csharp/package.json
packages/electron/package-lock.json
packages/electron/package.json
packages/electron/src/preload-localStore.ts
packages/integration-test/package-lock.json
packages/integration-test/package.json
packages/react/package-lock.json
packages/react/package.json

- Update Client Version
- Update Tool Version

update version to 1.6.7 

---

packages/csharp/PortingAssistant/PortingAssistant.Common/Utils/TelemetryCollectionUtils.cs
packages/react/src/components/Setup/ProfileSelection.tsx
packages/react/src/constants/externalUrls.ts
packages/react/src/containers/Setup.tsx

- Add CLI link to Profile Setup Page

feat: add link to CLI exe release

---

packages/csharp/PortingAssistant/PortingAssistant.Api/PortingAssistant.Api.csproj
packages/csharp/PortingAssistant/PortingAssistant.Common/PortingAssistant.Common.csproj
packages/csharp/PortingAssistant/PortingAssistant.Telemetry/PortingAssistant.Telemetry.csproj
packages/csharp/PortingAssistant/PortingAssistant.UnitTests/PortingAssistant.UnitTests.csproj
packages/csharp/PortingAssistant/PortingAssistant.VisualStudio/PortingAssistant.VisualStudio.csproj
packages/integration-test/src/canary.spec.ts
packages/integration-test/src/stability.spec.ts

Update PA Client version and add integration test for Visual Basic solutions

test: add vb ui integration tests

---

.github/workflows/semantic-pr-check.yml

add action to check semantic pull request title

build: add semantic pr check

---

packages/csharp/PortingAssistant/PortingAssistant.Telemetry/Program.cs
packages/csharp/PortingAssistant/PortingAssistant.Telemetry/Utils/LogUploadUtils.cs
packages/electron/src/electron-backend.ts

- Enable share metric
- Tested with Gamma Endpoint

fix: fix logs upload

---

lerna.json
package-lock.json
package.json
packages/csharp/PortingAssistant/PortingAssistant.Api/PortingAssistant.Api.csproj
packages/csharp/PortingAssistant/PortingAssistant.Common/PortingAssistant.Common.csproj
packages/csharp/PortingAssistant/PortingAssistant.Telemetry/PortingAssistant.Telemetry.csproj
packages/csharp/PortingAssistant/PortingAssistant.UnitTests/PortingAssistant.UnitTests.csproj
packages/csharp/PortingAssistant/PortingAssistant.VisualStudio/PortingAssistant.VisualStudio.csproj
packages/csharp/package-lock.json
packages/csharp/package.json
packages/electron/package-lock.json
packages/electron/package.json
packages/electron/src/preload-localStore.ts
packages/integration-test/package-lock.json
packages/integration-test/package.json
packages/react/package-lock.json
packages/react/package.json

bump version to 1.7.0
update pa client version to include changes for vb.net support

chore: bump version to 1.7.0

---

packages/csharp/PortingAssistant/PortingAssistant.Api/Application.cs

wrap solution path argument in quotes to avoid issues with spaces
manually tested both solution with spaces in path, and solution with no spaces in path to verify no regressions. both cases passed.

fix: open in vs action

---

packages/csharp/package-lock.json
packages/integration-test/package-lock.json
packages/integration-test/package.json

update npm packages in csharp and integration test packages
test integration tests still run, and no issues in csharp connection when running application

chore: update additional npm packages

---

package-lock.json
packages/react/package-lock.json

feat: update package lock

---

packages/react/package-lock.json

chore: update ts

---

packages/react/package-lock.json

chore: update pacakge lock

---

packages/react/package-lock.json
packages/react/package.json

chore: revert ts and ts-jest

---

lerna.json
package-lock.json
package.json
packages/csharp/PortingAssistant/PortingAssistant.Api/PortingAssistant.Api.csproj
packages/csharp/PortingAssistant/PortingAssistant.Common/PortingAssistant.Common.csproj
packages/csharp/PortingAssistant/PortingAssistant.Telemetry/PortingAssistant.Telemetry.csproj
packages/csharp/PortingAssistant/PortingAssistant.UnitTests/PortingAssistant.UnitTests.csproj
packages/csharp/PortingAssistant/PortingAssistant.VisualStudio/PortingAssistant.VisualStudio.csproj
packages/csharp/package-lock.json
packages/csharp/package.json
packages/electron/package-lock.json
packages/electron/package.json
packages/electron/src/preload-localStore.ts
packages/integration-test/package-lock.json
packages/integration-test/package.json
packages/react/package-lock.json
packages/react/package.json

- Bump PA Version
- Bump PA Client Version
- Build successfully locally and on Codebuild dev project
- Unit/Integration Tests Passed

chore: bump version

---

packages/csharp/PortingAssistant/PortingAssistant.Api/Application.cs
packages/csharp/PortingAssistant/PortingAssistant.Api/Program.cs

fix: remove customercontrib config reader

---

packages/integration-test/src/canary.spec.ts
packages/integration-test/src/testRunner.ts

- Fix UI component's id for integ tests
- Integ tests passed locally

fix: fix ui components for integ tests

---

package.json
packages/csharp/PortingAssistant/PortingAssistant.Api/PortingAssistant.Api.csproj
packages/csharp/PortingAssistant/PortingAssistant.Common/PortingAssistant.Common.csproj
packages/csharp/PortingAssistant/PortingAssistant.Telemetry/PortingAssistant.Telemetry.csproj
packages/csharp/PortingAssistant/PortingAssistant.UnitTests/PortingAssistant.UnitTests.csproj
packages/csharp/PortingAssistant/PortingAssistant.VisualStudio/PortingAssistant.VisualStudio.csproj
packages/csharp/package.json
packages/electron/package.json
packages/integration-test/package.json
packages/react/package.json
packages/react/src/constants/externalUrls.ts
packages/react/src/containers/Dashboard.tsx

update ide extension link to point to toolkit for refactoring
run debugging and verify the changes

docs: update link to tr
